import "./globals.css";
import { type Metadata } from "next";
import { type ReactNode } from "react";
import pretendard from "./_font/pretendard";
import Header from "./_component/header";
import Footer from "./_component/footer";
import { ThemeProvider } from "next-themes";

type Props = {
  children: ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`${pretendard.className} bg-gray-50 dark:bg-gray-950 text-gray-950 dark:text-gray-50`}
      >
        <ThemeProvider attribute="class">
          <div className="px-4 max-w-screen-md mx-auto min-h-dvh flex flex-col">
            <Header />
            <div className="px-2 grow">{children}</div>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
