import "./globals.css";
import { type Metadata } from "next";
import { type ReactNode } from "react";
import pretendard from "./_font/pretendard";
import Header from "./_component/header";
import Footer from "./_component/footer";
import { ThemeProvider } from "next-themes";

type Props = {
  children: ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`${pretendard.className} min-h-dvh max-w-screen-md mx-auto flex flex-col bg-white dark:bg-black`}
      >
        <ThemeProvider attribute="class">
          <Header />
          <div className="grow">{children}</div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
